name: Tauri Bundle

on:
  # 手動実行（推奨）
  workflow_dispatch:
  # タグ作成時（任意: v*）で自動ビルド
  push:
    tags:
      - "v*"

jobs:
  bundle:
    name: Bundle (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            app/package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install NSIS (Windows)
        if: runner.os == 'Windows'
        run: choco install nsis -y

      - name: Install Linux deps (GTK/WebKit/GLib)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libglib2.0-dev \
            libgtk-3-dev \
            libgdk-pixbuf2.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf
          # WebKitGTK: prefer 4.1, fallback to 4.0 if unavailable on the image
          sudo apt-get install -y libwebkit2gtk-4.1-dev || sudo apt-get install -y libwebkit2gtk-4.0-dev

      - name: Install root deps (CLI)
        run: npm ci

      - name: Install app deps
        run: npm ci
        working-directory: app

      - name: Build (tauri bundle)
        run: npm run build

      - name: Upload bundles
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundles-${{ runner.os }}
          path: |
            src-tauri/target/release/bundle/**
          if-no-files-found: error
          compression-level: 6
